server:
    port: 8080

eureka:
    instance:
        hostname: localhost
        port: 9000
    client:
        serviceUrl: 
            defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka

spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            routes:
            - id: alunoModule
              uri: lb://ALUNO-SERVICE
              predicates:
              - Path=/alunos/**
            - id: projetoModule
              uri: lb://PROJETO-SERVICE
              predicates:
              - Path=/projetos/**